name: Daily Threat Intelligence Collection

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  collect-intel:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests configparser pandas
        
    - name: Run fetch_intel.py
      run: python script/fetch_intel.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add ti_collections/*.csv README.md
        git commit -m "Automated threat intelligence update"
        git push